default:
  debug: 0
oci_conf:
  bootstrap.servers: "<OCI-ENDPOINT>"
  security.protocol: 'SASL_SSL'
  #ssl.ca.location: '/home/user/cacert.pem'
  sasl.mechanism: 'PLAIN'
  sasl.username: '<OCI_TENANT>/<OCI_USERNAME>/OCI_STREAMPOOL_ID'
  sasl.password: '<OCI-Token>' 
  group.id: '<UNIIQUE-GROUPNAME>'
  topic: '<OCI-Streamname>'

kentik_auth:
  flow_url: 'https://flow.kentik.com/chf?sender_id='
  api_url: 'https://api.kentik.com'
  X-CH-Auth-Email: '<KENTIK_USER>'
  X-CH-Auth-API-Token: '<KENTIK_API_TOKEN>'
  X-CH-App-Protocol: '0'
  Content-Type: 'application/influx'

kentik_device:
  company_id: '<KENTIK_COMPANY_ID>'
  device_name: '<KENTIK_OCI_DEVICE_NAME>'
  device_id: '<KENTIK_DEVICE_ID>'


